name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes introduced by the latest change'
author: 'Enrico Campidoglio'
inputs:
  repo-token: 
    description: 'The GITHUB_TOKEN used to authenticate to the current build'
    required: true
outputs:
  release-url: 
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'dist/index.js'
